version: '3.8'

services:
  ecommerce-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"  
    depends_on:
      - ecommerce-backend

  ecommerce-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    ports:
      - "5000:5000" 
    environment:
      MONGO_URL: mongodb://ecommerce-mongo:27018/ecommerce
    depends_on:
      - ecommerce-mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5

  ecommerce-mongo:
    image: mongo:5.0
    container_name: ecommerce_mongo
    ports:
      - "27017:27017"  
    volumes:
      - ecommerce_mongo_data:/data/db

volumes:
  ecommerce_mongo_data:

