version: '3.8'
<<<<<<< HEAD
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map Nginx port to localhost
=======

services:
  ecommerce-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    ports:
      - "3000:3000"  #
>>>>>>> d04f83b (Initial commit of the Yolo Ecommerce project with frontend and backend Docker setup)
    depends_on:
      - ecommerce-backend

<<<<<<< HEAD
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map backend port
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Map MongoDB port
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
=======
  ecommerce-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    ports:
      - "5000:5000" 
    environment:
      MONGO_URL: mongodb://ecommerce-mongo:27018/ecommerce 
    depends_on:
      - ecommerce-mongo

  ecommerce-mongo:
    image: mongo:5.0
    container_name: ecommerce_mongo
    ports:
      - "27017:27017"  
    volumes:
      - ecommerce_mongo_data:/data/db

volumes:
  ecommerce_mongo_data:
>>>>>>> d04f83b (Initial commit of the Yolo Ecommerce project with frontend and backend Docker setup)
